networks:
  openim:
    external: true
    name: openim

services:
  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: grafana
    user: root
    restart: always
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      TZ: Asia/Shanghai
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_SESSION_COOKIE_SAMESITE: none
      GF_SESSION_COOKIE_SECURE: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - "${DATA_DIR}/data:/var/lib/grafana"
    networks:
      - openim
