networks:
  openim:
    external: true
    name: openim

services:
  openim-chat:
    image: ${OPENIM_CHAT_IMAGE}
    container_name: openim-chat
    ports:
      - "${CHAT_API_PORT}:10008"
      - "${ADMIN_API_PORT}:10009"
    environment:
      TZ: Asia/Shanghai
      CHATENV_MONGODB_ADDRESS: ${MONGO_ADDRESS}
      CHATENV_MONGODB_USERNAME: ${MONGO_USERNAME}
      CHATENV_MONGODB_PASSWORD: ${MONGO_PASSWORD}
      CHATENV_DISCOVERY_ETCD_ADDRESS: ${ETCD_ADDRESS}
      CHATENV_REDIS_ADDRESS: ${REDIS_ADDRESS}
      CHATENV_REDIS_PASSWORD: ${REDIS_PASSWORD}
      CHATENV_SHARE_OPENIM_SECRET: ${OPENIM_SECRET}
      CHATENV_SHARE_OPENIM_APIURL: ${API_URL}
      CHATENV_LOG_ISSTDOUT: ${LOG_IS_STDOUT}
      CHATENV_LOG_REMAINLOGLEVEL: ${LOG_LEVEL}
    restart: always
    networks:
      - openim
