networks:
  openim:
    external: true
    name: openim

services:
  mongo:
    image: "${MONGO_IMAGE}"
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "${DATA_DIR}/data/db:/data/db"
      - "${DATA_DIR}/data/logs:/data/logs"
      - "${DATA_DIR}/scripts:/docker-entrypoint-initdb.d:ro"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_OPENIM_USERNAME: ${MONGO_USERNAME}
      MONGO_OPENIM_PASSWORD: ${MONGO_PASSWORD}
    restart: always
    command: ["mongod", "--wiredTigerCacheSizeGB", "1", "--auth"]
    networks:
      - openim
