networks:
  openim:
    external: true
    name: openim

services:
  etcd:
    image: "${ETCD_IMAGE}"
    container_name: etcd
    ports:
      - "${ETCD_CLIENT_PORT}:2379"
      - "${ETCD_PEER_PORT}:2380"
    volumes:
      - "${DATA_DIR}/data:/etcd-data"
    environment:
      TZ: Asia/Shanghai
      ETCD_NAME: s1
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: s1=http://etcd:2380
      ETCD_INITIAL_CLUSTER_TOKEN: tkn
      ETCD_INITIAL_CLUSTER_STATE: new
      ALLOW_NONE_AUTHENTICATION: "no"
    restart: always
    networks:
      - openim
