networks:
  openim:
    external: true
    name: openim

services:
  redis:
    image: "${REDIS_IMAGE}"
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${DATA_DIR}/data:/data"
    environment:
      TZ: Asia/Shanghai
    restart: always
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--appendonly",
        "yes",
      ]
    networks:
      - openim
