networks:
  openim:
    external: true
    name: openim

services:
  alertmanager:
    image: ${ALERTMANAGER_IMAGE}
    container_name: alertmanager
    restart: always
    ports:
      - "${ALERTMANAGER_PORT}:9093"
    volumes:
      - "${DATA_DIR}/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
      - "${DATA_DIR}/config/email.tmpl:/etc/alertmanager/email.tmpl"
    environment:
      TZ: Asia/Shanghai
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--web.listen-address=:9093"
      - "--cluster.listen-address="
    networks:
      - openim
