networks:
  openim:
    external: true
    name: openim

services:
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: prometheus
    restart: always
    user: root
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - "${DATA_DIR}/config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "${DATA_DIR}/config/instance-down-rules.yml:/etc/prometheus/instance-down-rules.yml"
      - "${DATA_DIR}/data:/prometheus"
    environment:
      TZ: Asia/Shanghai
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.listen-address=:9090"
    networks:
      - openim
